### PR TITLE
Add health handler

### PR DESCRIPTION
**Pull request by zhouzhuojie**
Tested locally for the health endpoint

```
curl localhost:18000/api/v1/health 
```

### CODE REVIEW

**Comment by zhouzhuojie** [comment]
Fixes #102

**Comment by marceloboeira** [comment]
👍

**Comment by mukesh-p** [comment]
I was setting this health-check for a pod in GKE as a readiness probe. By default when I hit the server with curl from localhost on the path given it returns with "Not authorized" response. When I passed authorization headers along with curl then it worked. The problem is these authorization headers are not ideal for GKE HC probes and Ingress is always marked as unhealthy. Do we have some URL paths that gives back a 200 OK response without any need to authorize? I believe for HC probes it should be as simple as possible to get know about the server health.

**Comment by zhouzhuojie** [comment]
@mukesh-p did you turn on the `FLAGR_BASIC_AUTH_ENABLED`? If so, you may also want to whitelist the `/api/v1/health` endpoint. 

You can set 
```
# Default
FLAGR_BASIC_AUTH_WHITELIST_PATHS=/api/v1/flags,/api/v1/evaluation

# You can add /api/v1/health or change it
FLAGR_BASIC_AUTH_WHITELIST_PATHS=/api/v1/flags,/api/v1/evaluation,/api/v1/health
``` 

I'm also thinking of adding `/api/v1/health` to the default.

**Comment by zhouzhuojie** [comment]
Related https://github.com/checkr/flagr/pull/407

**Pull request merged**
