### PR TITLE
Adding support for notifying other services via webhooks

### PR DESCRIPTION
**Pull request by sorenmat**
## Description

Adding a webhook for notifying other services when a change happens in flagr.

Pretty much a copy of #410 which seems to be stale. Simplified it a bit and removed the slack
portion of it, since there seems to be some discussions on how to implement that in a sane way.

After this is merged we can rebase #410 and get the slack notification going

## Motivation and Context

Useful for keeping an audit style log in another system

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by marceloboeira** [comment]
Could you open this PR against https://github.com/openflagr/flagr ?

**Comment by sorenmat** [comment]
Pinging @pacoguzman @zhouzhuojie since you were involved in #410

**Comment by sorenmat** [comment]
Sure :)

**Comment by sorenmat** [comment]
will open against openflagr/flagr

**Comment by sorenmat** [comment]
PR against openflagr https://github.com/openflagr/flagr/pull/38

**Comment by marceloboeira** [comment]
👍🏼

**Pull request closed without merging**
